dist: trusty

language: php

php:
  - 7.2
  - 7.3

cache:
  directories:
    - $HOME/.cache/composer

env:
  - PHPUNIT_CONFIG="phpunit.xml" SYMFONY_VERSION="~3.4.0"
  - PHPUNIT_CONFIG="phpunit.xml" SYMFONY_VERSION="~4.3.0"
  - PHPUNIT_CONFIG="phpunit.xml" SYMFONY_VERSION="^4.4@dev"

matrix:
  include:
    - php: 7.2
      env: PHPUNIT_CONFIG="phpunit.xml" SYMFONY_VERSION="~3.4.0" DEPS="low"
    - php: 7.3
      env: RUN_PHPSTAN="yes"
    - php: 7.3
      env: RUN_PSALM="yes"

branches:
  only:
    - master
    - /^\d.\d+$/

before_script:
  - phpenv config-rm xdebug.ini || true
  - echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

  # Read-only OAuth token to work around GitHub API rate limits
  - composer config -g github-oauth.github.com "4b3b0a83ea27d9544d3608a384c7a14625a98804"

  # Install Flex as a global dependency to enable usage of extra.symfony.require
  # while keeping Flex recipes from applying
  - composer global require --no-scripts symfony/flex

  - if [ "$SYMFONY_VERSION" != "" ] ; then composer config extra.symfony.require $SYMFONY_VERSION ; fi

  - |
    if [ "$DEPS" = "low" ] ; then
      composer update --no-suggest --prefer-dist --prefer-lowest --prefer-stable
    else
      composer update --no-suggest --prefer-dist
    fi

script:
  - composer validate --strict
  - if [ "$PHPUNIT_CONFIG" != "" ] ; then vendor/bin/phpunit -c $PHPUNIT_CONFIG --colors=always ; fi
  - if [ "$RUN_PHPSTAN" != "" ] ; then composer phpstan ; fi
  - if [ "$RUN_PHPSTAN" != "" ] ; then composer phpstan-tests ; fi
  - if [ "$RUN_PSALM" != "" ] ; then composer psalm ; fi

notifications:
  email: false
  slack:
    rooms:
      - secure: "Pe7Hx7N3bn7QEH+ZdyYXCaItlSHASELuDddd7N3Kuc1wq3JNB6jT1gjp2Of6JyMrvfh6EPBcfxcmFLvZ+c2mFupf7QJzVRY/8NRytCvqUbyccvg9XZTrV1bd6I4fR2DnukuaHtR1cLMxomZx6q/C/eQAk2Lvoq0kUqsrljfPjR+YPrYes2ZDh7C7zDZxaI42jCqb52l0QOyAYE5poeGZMoCxiFDXhuVNs5QUVcxfpNXDnUQyWTYdWJNaprhwTf2k68ypumPqRtw2yzHm+0uKOXHUTN3YqLvPYj3OD0WKZsk8KHloLTF55eRL2PNnwpKnoyEfybtJPXnWKJFNMys17o05R6mnbhMTRT1mUjaZ0RCVYcrqMXvCu3aHSHk+75buldyR3Ds5H1PaTztWaonRe6k+2+zZaYtQlrSUBzwzu5OusAfeVz5bD0vDC+sBOW3Cl2Qpkctn28Fy+Us6CqJzF0QHmp9pMRdj2p4gUHDaDrlvUWy0J6oCZF5B8Zi8QQ80898SlTIwsvtQmF46PE6Tu0jtFZmxLflJrI2qtlXYP1hw2WT2uQRNmTRVmRHXkA5Zc6GhUrk5a5On+Kus24fKIxMNMbbl8fvWIzLSnR8b7IjZ00bUx04gZKVS+4ky7Z5bofyCFeSdbz4dLWiNWQCBK6/mdxDaF2Mq7f5IQNCaD/E="
    on_success: change
    on_failure: always
    on_pull_requests: false

git:
  depth: 1
