services:
    netgen_layouts.contentful.collection.query_type_handler.search:
        class: Netgen\Layouts\Contentful\Collection\QueryType\Handler\ContentfulSearchHandler
        arguments:
            - "@netgen_layouts.contentful.service"
        tags:
            - { name: netgen_layouts.query_type_handler, type: contentful_search }
